// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// parallel_norms.cpp
cpp11::doubles cpp_row_norms(cpp11::doubles_matrix<> x);
extern "C" SEXP _cpp11openmp_cpp_row_norms(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_row_norms(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(x)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp11openmp_cpp_row_norms", (DL_FUNC) &_cpp11openmp_cpp_row_norms, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp11openmp(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
